version: '3'

tasks:

  run:
    cmds:
      - go build .
      - rofi -show grofi -modi "grofi:$HOME/git/grofi/grofi"

  install:
    cmds:
      - go build .
      - mv grofi /usr/local/bin/grofi
      - chmod u+x /usr/local/bin/grofi
